export const appRoutes = {
  home: '/',
  departments: '/departments',
  disciplines: '/disciplines',
  disciplinesInStudyPlans: '/disciplines-in-study-plans',
  faculties: '/faculties',
  specialities: '/specialties',
  academicLoads: '/academic-loads',
  standards: '/standards',
  studyPlans: '/study-plans',
  programs: '/programs',
  programSections: '/program-sections',
  programSubsections: '/program-subsections',
  users: '/users',
} as const;
